kind: pipeline
type: kubernetes
name: biehler-josef
steps:
- name: install
  image: node:10
  commands:
    - set -e
    - npm install
- name: twitter
  image: node:10
  commands:
    - npm run twitter 
  environment:
    TWTR_ASECRET:
      from_secret: TWTR_ASECRET
    TWTR_ATOKEN:
      from_secret: TWTR_ATOKEN
    TWTR_CKEY:
      from_secret: TWTR_CKEY
    TWTR_CSECRET:
      from_secret: TWTR_CSECRET
- name: contributions
  image: node:10
  commands:
    - npm run contributions
  environment:
    GITHUB_TOKEN:
      from_secret: GITHUB_TOKEN
- name: githubcloud
  image: node:10
  commands:
    - npm run githubcloud
  environment:
     GITHUB_TOKEN:
      from_secret: GITHUB_TOKEN