kind: pipeline
type: kubernetes
name: biehler-josef
steps:
- name: install
  image: node:10
  commands:
    - set -e
    - npm install
- name: twitter
  image: node:10
  commands:
    - npm run twitter 