apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: biehlerjosef-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: biehler-josef.de
    http:
      - path: /
        backend:
          serviceName: biehlerjosef-service
          servicePort: 80